### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'grad'

### ISSUE THREAD

**Issue by davidlowjw** [bkj/ulm-basenet#2]
Hi Ben, 

I ran the run.sh and everything works fine until train_classifier.py, here is the error:

```
train_epoch:train:   0%|                               | 0/1042 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train_classifier.py", line 177, in <module>
    save_prefix=os.path.join(args.outpath, 'cl_ft_last1'),
  File "/home/david/ulm-basenet/ulmfit.py", line 455, in basenet_train
    train = model.train_epoch(dataloaders, mode='train', compute_acc=False)
  File "/home/david/anaconda3/envs/ulm_env/lib/python3.6/site-packages/basenet/basenet.py", line 255, in train_epoch
    **kwargs,
  File "/home/david/anaconda3/envs/ulm_env/lib/python3.6/site-packages/basenet/basenet.py", line 219, in _run_epoch
    loss, metrics = batch_fn(data, target, metric_fns=metric_fns)
  File "/home/david/anaconda3/envs/ulm_env/lib/python3.6/site-packages/basenet/basenet.py", line 164, in train_batch
    grad_norm = torch.nn.utils.clip_grad_norm(self.params, self.clip_grad_norm)
  File "/home/david/anaconda3/envs/ulm_env/lib/python3.6/site-packages/torch/nn/utils/clip_grad.py", line 18, in clip_grad_norm
    parameters = list(filter(lambda p: p.grad is not None, parameters))
  File "/home/david/anaconda3/envs/ulm_env/lib/python3.6/site-packages/torch/nn/utils/clip_grad.py", line 18, in <lambda>
    parameters = list(filter(lambda p: p.grad is not None, parameters))
AttributeError: 'dict' object has no attribute 'grad'
```

Do you have any clue on how to resolve this?

**Comment by bkj** [comment]
Looks like a bug in `basenet` -- I should update the installation instructions here to referenced a fixed commit of that repo, since it's under very active development.

Can you post your python and torch versions here?  Then I can try to track down the bug.

**Comment by elyase** [comment]
@bkj : it would be great if you could you post the versions that are working for you. I was planning to do a dependency free (may be only pytorch 0.4) version of ulmfit but it would be better if I could base it on your work here (I might also strip out the basenet dependencies).

**Comment by cindyll00** [comment]
@davidlowjw I also have this problem.Did you solve this problem? My python is 3.6.6 and torch is 0.3.1

**Comment by cindyll00** [comment]
@bkj Hi, can you fix this bug? I have the same problem about "AttributeError: 'dict' object has no attribute 'grad'". Python 3.6.6 and Torch 0.3.1 ~ Looking forward to your reply.

**Comment by bkj** [comment]
I fixed a bug here:

  https://github.com/bkj/basenet/blob/master/basenet/basenet.py#L168

where `clip_grad_norm` didn't work for optimizer parameters like `[{'params' : ..., ...},...]`

**Comment by cindyll00** [comment]
@bkj It's OK. Thank you ~

**Comment by bkj** [comment]
I ran `train_classifier.py` again w/ the update and got the same accuracy as before, so I'll close this for now.  You can reopen if you run into similar issues in the future.
